model:
  energy_predictor:
    class_path: attribute_predictors.ConvLSTMLinearDAP
    init_args:
      n_speaker_dim: 16
      in_dim: 520
      out_dim: 1
      reduction_factor: 16
      n_backbone_layers: 3
      n_hidden: 256
      kernel_size: 5
      p_dropout: 0.5
      target_offset: -0.75
      lstm_type: bilstm
  energy_predictor_loss:
    class_path: loss.AttributeRegressionLoss
    init_args:
      prefix: "energy_"
      weight: 1.0